# Generated by Django 2.2.5 on 2019-09-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='user_app.File'),
        ),
    ]
