# Generated by Django 2.2.5 on 2019-09-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20190919_0824'),
        ('user_app', '0002_user_isadmin'),
    ]

    operations = [
    ]
