# Generated by Django 2.2.5 on 2019-09-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_merge_20190921_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='user_app.User'),
            preserve_default=False,
        ),
    ]
