# Generated by Django 2.2.5 on 2019-09-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20190922_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='file_id',
            new_name='file',
        ),
    ]
