# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-22 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20190922_1702'),
        ('user_app', '0006_auto_20190922_1346'),
    ]

    operations = [
    ]
