# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20190923_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user_app.File'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user_app.User'),
        ),
    ]
