# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20190923_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
    ]
