# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_user_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
